### ISSUE TITLE
Automata input format

### ISSUE THREAD

**Issue by M42** [computation-hs/comp-models#16]
We should decide a standard format for reading and writing automatas. Something like:
``` Haskell
dfa
alpha: [a,b,c]
states: [A,B,C]
A a -> A
A b -> B
A c -> B
B a -> B
B c -> C
C a -> C
```
(Maybe `alpha` and `states` are not necessary)

**Comment by pbaeyens** [comment]
[YAML](http://www.yaml.org/spec/1.2/spec.html) seems quite similar to this, except for the transition function definition which might be implemented as a list of triples. There is [a Haskell YAML parser](http://hackage.haskell.org/package/YamlReference) that might save us some work.

**Comment by M42** [comment]
Maybe something similar to:
``` YAML
dfa
alpha: [a,b,c]
states: [A,B,C]
transitions:
 - A: {a:A, b:B, c:B}
 - B: {a:B, c:C}
 - C: {a:C}
```
But I don't see how we can extend this format to NFA automata.
